# Extra completion functions (e.g. cargo/rustup); must come before compinit in cachyos-config.zsh
fpath=(~/.zfunc $fpath)

source /usr/share/cachyos-zsh-config/cachyos-config.zsh
export PATH="$HOME/.local/bin:$PATH"

# Claude Code
alias cc='claude'
alias ccc='claude --continue'
alias ccr='claude --resume'
alias pi='sudo pacman -S'
alias pr='sudo pacman -Rns'
alias nv='nvim'

# Prompt: Starship instead of the Powerlevel10k theme that cachyos-config.zsh loads
(( $+functions[powerlevel10k_plugin_unload] )) && powerlevel10k_plugin_unload
eval "$(starship init zsh)"

# jonaszfetch: image behind fastfetch output (kitty only)
ff() {
    clear
    kitten icat --clear
    kitten icat --z-index=-1 --place 80x14@0x0 --transfer-mode=file ~/Pictures/fetchimage.png
    fastfetch --logo none --pipe false | sed 's/^/                                  /'
    printf '\e[15;1H'  # move the prompt below the 14-row image
}

# Wallpaper palette theme (see ~/Images/wallpaper-palette.txt)
# File colors for ls and tab completion, generated by vivid
(( $+commands[vivid] )) && export LS_COLORS="$(vivid generate ~/.config/vivid/themes/seed.yml)"
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Command-line highlighting and suggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#606990'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#D16A8A'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#B07AE6'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#8B63E0'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#8B63E0'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#8B63E0'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#8B63E0'
ZSH_HIGHLIGHT_STYLES[function]='fg=#8B63E0'
ZSH_HIGHLIGHT_STYLES[command]='fg=#8B63E0'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#B07AE6,italic'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#7AB0D8'
ZSH_HIGHLIGHT_STYLES[path]='fg=#C9CFE0,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#7AB0D8'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#5B8BE8'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#5B8BE8'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#6FB8A0'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#6FB8A0'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#6FB8A0'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#CDB37E'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#CDB37E'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#7AB0D8'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#606990'

# fzf colors (also used by the tab menu and zi)
FZF_DEFAULT_OPTS='--color=bg+:#232838,fg:#959FB8,fg+:#C9CFE0,hl:#8B63E0,hl+:#B07AE6,info:#606990,prompt:#5B8BE8,pointer:#8B63E0,marker:#6FB8A0,spinner:#7067D6,header:#7AB0D8,border:#30374A'
export FZF_DEFAULT_OPTS

# Fish-like extras (ported from cachyos-fish-config)
# Pick up newly installed programs right away (no shell restart needed)
zstyle ':completion:*' rehash true

# Fuzzy tab-completion menu
source ~/.local/share/zsh/fzf-tab/fzf-tab.plugin.zsh
zstyle ':fzf-tab:*' use-fzf-default-opts yes

# eza in place of ls
if (( $+commands[eza] )); then
    alias ls='eza -al --color=always --group-directories-first --icons=always' # preferred listing
    alias la='eza -a --color=always --group-directories-first --icons=always'  # all files and dirs
    alias ll='eza -l --color=always --group-directories-first --icons=always'  # long format
    alias lt='eza -aT --color=always --group-directories-first --icons=always' # tree listing
    alias l.="eza -a | grep -e '^\.'"                                          # show only dotfiles
fi

# Colored man pages with bat
if (( $+commands[bat] )); then
    export MANROFFOPT="-c"
    export MANPAGER="sh -c 'col -bx | bat -l man -p'"
fi

# zoxide: `z <part of a folder name>` jumps there, `zi` picks with fzf
if (( $+commands[zoxide] )); then
    eval "$(zoxide init zsh)"
    alias za='zoxide add'     # remember a folder now
    alias zq='zoxide query'   # print where `z <name>` would go
    alias zr='zoxide remove'  # forget a folder
fi
