# font_family      family="Ioskeley Mono Term"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto


# BEGIN_KITTY_FONTS
font_family      postscript_name=Ioskeley-Mono-Term-Semi-Condensed
bold_font        postscript_name=Ioskeley-Mono-Term-Bold-Semi-Condensed
italic_font      postscript_name=Ioskeley-Mono-Term-Semi-Condensed-Italic
bold_italic_font postscript_name=Ioskeley-Mono-Term-Bold-Semi-Condensed-Italic
# END_KITTY_FONTS

font_size        10.0

background_opacity        0.95
window_padding_width      6
hide_window_decorations   yes
confirm_os_window_close   0
remember_window_size      no
initial_window_width      120c
initial_window_height     34c
enable_audio_bell         no
visual_bell_duration      0
cursor_shape              block
cursor_blink_interval     0
mouse_hide_wait           2.0
url_style                 curly
detect_urls               yes
scrollback_lines          20000
scrollback_pager_history_size 20
copy_on_select            clipboard
strip_trailing_spaces     smart
paste_actions             quote-urls-at-prompt,confirm

include theme.conf

# Per-session overrides: x11.conf under Window Maker, wayland.conf under Hyprland
include ${XDG_SESSION_TYPE}.conf
