-- terminal: draws with the terminal's own 16 colors (kitty's palette, which follows the wallpaper).
-- Needs `termguicolors` off; the background is left transparent so kitty's shows through.
--   0 black   1 red   2 green   3 yellow   4 blue   5 magenta   6 cyan   7 white
--   8-15 are the bright versions

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = false
vim.o.background = "dark"
vim.g.colors_name = "terminal"

local NONE = "NONE"

local groups = {
  -- Editor UI
  Normal         = { ctermfg = 15, ctermbg = NONE },
  NormalNC       = { ctermfg = 15, ctermbg = NONE },
  NormalFloat    = { ctermfg = 15, ctermbg = 0 },
  FloatBorder    = { ctermfg = 8, ctermbg = 0 },
  FloatTitle     = { ctermfg = 4, ctermbg = 0, bold = true },
  EndOfBuffer    = { ctermfg = 0 },
  NonText        = { ctermfg = 8 },
  Whitespace     = { ctermfg = 8 },
  SpecialKey     = { ctermfg = 8 },
  CursorLine     = { ctermbg = 0 },
  CursorColumn   = { ctermbg = 0 },
  ColorColumn    = { ctermbg = 0 },
  LineNr         = { ctermfg = 8 },
  CursorLineNr   = { ctermfg = 12, bold = true },
  SignColumn     = { ctermbg = NONE },
  FoldColumn     = { ctermfg = 8, ctermbg = NONE },
  Folded         = { ctermfg = 7, ctermbg = 0 },
  WinSeparator   = { ctermfg = 8 },
  VertSplit      = { ctermfg = 8 },
  StatusLine     = { ctermfg = 15, ctermbg = 0 },
  StatusLineNC   = { ctermfg = 8, ctermbg = 0 },
  TabLine        = { ctermfg = 7, ctermbg = 0 },
  TabLineFill    = { ctermbg = NONE },
  TabLineSel     = { ctermfg = 0, ctermbg = 4, bold = true },
  WinBar         = { ctermfg = 7 },
  WinBarNC       = { ctermfg = 8 },
  Pmenu          = { ctermfg = 7, ctermbg = 0 },
  PmenuSel       = { ctermfg = 0, ctermbg = 4, bold = true },
  PmenuSbar      = { ctermbg = 0 },
  PmenuThumb     = { ctermbg = 8 },
  PmenuKind      = { ctermfg = 4, ctermbg = 0 },
  PmenuExtra     = { ctermfg = 8, ctermbg = 0 },
  Visual         = { ctermfg = 0, ctermbg = 12 },
  VisualNOS      = { ctermfg = 0, ctermbg = 12 },
  Search         = { ctermfg = 0, ctermbg = 3 },
  IncSearch      = { ctermfg = 0, ctermbg = 11 },
  CurSearch      = { ctermfg = 0, ctermbg = 11 },
  Substitute     = { ctermfg = 0, ctermbg = 1 },
  MatchParen     = { ctermfg = 13, bold = true, underline = true },
  Directory      = { ctermfg = 4, bold = true },
  Title          = { ctermfg = 4, bold = true },
  Question       = { ctermfg = 2 },
  MoreMsg        = { ctermfg = 2 },
  ModeMsg        = { ctermfg = 7, bold = true },
  ErrorMsg       = { ctermfg = 1, bold = true },
  WarningMsg     = { ctermfg = 3 },
  WildMenu       = { ctermfg = 0, ctermbg = 4 },
  QuickFixLine   = { ctermbg = 0 },
  SpellBad       = { undercurl = true, ctermfg = 1 },
  SpellCap       = { undercurl = true, ctermfg = 3 },
  SpellLocal     = { undercurl = true, ctermfg = 6 },
  SpellRare      = { undercurl = true, ctermfg = 5 },
  Conceal        = { ctermfg = 8 },

  -- Syntax
  Comment        = { ctermfg = 8, italic = true },
  Constant       = { ctermfg = 3 },
  String         = { ctermfg = 2 },
  Character      = { ctermfg = 2 },
  Number         = { ctermfg = 3 },
  Boolean        = { ctermfg = 3 },
  Float          = { ctermfg = 3 },
  Identifier     = { ctermfg = 15 },
  Function       = { ctermfg = 4 },
  Statement      = { ctermfg = 5 },
  Conditional    = { ctermfg = 5 },
  Repeat         = { ctermfg = 5 },
  Label          = { ctermfg = 5 },
  Operator       = { ctermfg = 6 },
  Keyword        = { ctermfg = 5 },
  Exception      = { ctermfg = 1 },
  PreProc        = { ctermfg = 13 },
  Include        = { ctermfg = 13 },
  Define         = { ctermfg = 13 },
  Macro          = { ctermfg = 13 },
  Type           = { ctermfg = 12 },
  StorageClass   = { ctermfg = 5 },
  Structure      = { ctermfg = 12 },
  Typedef        = { ctermfg = 12 },
  Special        = { ctermfg = 6 },
  SpecialChar    = { ctermfg = 6 },
  Tag            = { ctermfg = 4 },
  Delimiter      = { ctermfg = 7 },
  SpecialComment = { ctermfg = 7, italic = true },
  Debug          = { ctermfg = 1 },
  Underlined     = { underline = true },
  Error          = { ctermfg = 1 },
  Todo           = { ctermfg = 0, ctermbg = 3, bold = true },
  Added          = { ctermfg = 2 },
  Changed        = { ctermfg = 3 },
  Removed        = { ctermfg = 1 },

  -- Treesitter
  ["@variable"]              = { ctermfg = 15 },
  ["@variable.builtin"]      = { ctermfg = 1 },
  ["@variable.parameter"]    = { ctermfg = 7 },
  ["@variable.member"]       = { ctermfg = 7 },
  ["@property"]              = { ctermfg = 7 },
  ["@constant"]              = { ctermfg = 3 },
  ["@constant.builtin"]      = { ctermfg = 3 },
  ["@module"]                = { ctermfg = 12 },
  ["@string"]                = { ctermfg = 2 },
  ["@string.escape"]         = { ctermfg = 6 },
  ["@string.regexp"]         = { ctermfg = 6 },
  ["@string.special.url"]    = { ctermfg = 4, underline = true },
  ["@number"]                = { ctermfg = 3 },
  ["@boolean"]               = { ctermfg = 3 },
  ["@type"]                  = { ctermfg = 12 },
  ["@type.builtin"]          = { ctermfg = 12, italic = true },
  ["@attribute"]             = { ctermfg = 13 },
  ["@function"]              = { ctermfg = 4 },
  ["@function.builtin"]      = { ctermfg = 4, italic = true },
  ["@function.method"]       = { ctermfg = 4 },
  ["@constructor"]           = { ctermfg = 12 },
  ["@keyword"]               = { ctermfg = 5 },
  ["@keyword.return"]        = { ctermfg = 5, italic = true },
  ["@keyword.import"]        = { ctermfg = 13 },
  ["@keyword.exception"]     = { ctermfg = 1 },
  ["@operator"]              = { ctermfg = 6 },
  ["@punctuation"]           = { ctermfg = 7 },
  ["@punctuation.bracket"]   = { ctermfg = 7 },
  ["@punctuation.delimiter"] = { ctermfg = 7 },
  ["@punctuation.special"]   = { ctermfg = 6 },
  ["@comment"]               = { link = "Comment" },
  ["@tag"]                   = { ctermfg = 5 },
  ["@tag.attribute"]         = { ctermfg = 7 },
  ["@tag.delimiter"]         = { ctermfg = 8 },
  ["@markup.heading"]        = { ctermfg = 4, bold = true },
  ["@markup.strong"]         = { bold = true },
  ["@markup.italic"]         = { italic = true },
  ["@markup.link"]           = { ctermfg = 4 },
  ["@markup.link.url"]       = { ctermfg = 4, underline = true },
  ["@markup.raw"]            = { ctermfg = 2 },
  ["@markup.list"]           = { ctermfg = 6 },
  ["@markup.quote"]          = { ctermfg = 7, italic = true },
  ["@diff.plus"]             = { ctermfg = 2 },
  ["@diff.minus"]            = { ctermfg = 1 },
  ["@diff.delta"]            = { ctermfg = 3 },

  -- LSP and diagnostics
  LspReferenceText           = { ctermbg = 0 },
  LspReferenceRead           = { ctermbg = 0 },
  LspReferenceWrite          = { ctermbg = 0 },
  LspInlayHint               = { ctermfg = 8, italic = true },
  DiagnosticError            = { ctermfg = 1 },
  DiagnosticWarn             = { ctermfg = 3 },
  DiagnosticInfo             = { ctermfg = 4 },
  DiagnosticHint             = { ctermfg = 6 },
  DiagnosticOk               = { ctermfg = 2 },
  DiagnosticUnderlineError   = { undercurl = true },
  DiagnosticUnderlineWarn    = { undercurl = true },
  DiagnosticUnderlineInfo    = { undercurl = true },
  DiagnosticUnderlineHint    = { undercurl = true },

  -- Diff and git signs
  DiffAdd        = { ctermfg = 2, ctermbg = 0 },
  DiffChange     = { ctermfg = 3, ctermbg = 0 },
  DiffDelete     = { ctermfg = 1, ctermbg = 0 },
  DiffText       = { ctermfg = 0, ctermbg = 3 },
  GitSignsAdd    = { ctermfg = 2 },
  GitSignsChange = { ctermfg = 3 },
  GitSignsDelete = { ctermfg = 1 },
  MiniDiffSignAdd    = { ctermfg = 2 },
  MiniDiffSignChange = { ctermfg = 3 },
  MiniDiffSignDelete = { ctermfg = 1 },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
