-- Generated by matugen from the current wallpaper — edit
-- ~/.config/matugen/templates/nvim-palette.lua instead of this file.
-- wall.* = the image's own colors (~/.local/bin/wallpalette), colors.* = matugen's.
return {
  bg0     = "{{wall.bg}}",
  bg      = "{{wall.bg}}",
  bg2     = "{{wall.surface}}",
  bg3     = "{{wall.surface2}}",
  surface = "{{colors.surface_container_highest.default.hex}}",
  overlay = "{{colors.outline_variant.default.hex}}",
  muted   = "{{colors.outline.default.hex}}",
  fgdim   = "{{wall.fgdim}}",
  fg      = "{{wall.fg}}",
  violet  = "{{wall.accent1}}",
  indigo  = "{{wall.accent2}}",
  orchid  = "{{wall.accent3}}",
  blue    = "{{colors.blue.default.hex | lighten: -8 | saturate: -20, "hsl"}}",
  slate   = "{{colors.on_surface_variant.default.hex}}",
  cyan    = "{{colors.cyan.default.hex | lighten: -8 | saturate: -20, "hsl"}}",
  teal    = "{{colors.green.default.hex | lighten: -8 | saturate: -20, "hsl"}}",
  rose    = "{{colors.red.default.hex | lighten: -8 | saturate: -20, "hsl"}}",
  gold    = "{{colors.yellow.default.hex | lighten: -8 | saturate: -20, "hsl"}}",
}
